/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import javax.swing.JOptionPane;
import pokemon.Batalla;
import pokemon.Entrenador;

/**
 *
 * @author WilmerTC
 */
public class Elegir extends javax.swing.JFrame {

    /**
     * Creates new form Elegir
     */
    private Entrenador yo;
    
    private Batalla batalla;
    private boolean enBatalla = false; // Variable para controlar si estás en una batalla

    public Elegir() {
        initComponents();
        String nombre = TxtUsuario.getText();
        yo = new Entrenador(nombre);
        batalla = new Batalla(yo);

        Esconder2();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        BtnPikachu = new javax.swing.JButton();
        BtnCharmander = new javax.swing.JButton();
        jTxtUser = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BtnBatalla = new javax.swing.JButton();
        BtnAtaqueNormal = new javax.swing.JButton();
        BtnLanzallamas = new javax.swing.JButton();
        BtnCapturar = new javax.swing.JButton();
        BtnAtaqueRapido = new javax.swing.JButton();
        BtnImpactrueno = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtEnemigo = new javax.swing.JTextField();
        TxtVida = new javax.swing.JTextField();
        TxtEnemigoNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokemon Wilmer Tenepe");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Charmander.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 256, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pikachu.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Selecciona un pokemon,para la aventura:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 454, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("BATALLA POKEMON");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre del jugador:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 94, 177, -1));

        TxtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 98, 129, -1));

        BtnPikachu.setBackground(new java.awt.Color(255, 255, 255));
        BtnPikachu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnPikachu.setForeground(new java.awt.Color(0, 0, 0));
        BtnPikachu.setText("Pikachu");
        BtnPikachu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPikachuActionPerformed(evt);
            }
        });
        jPanel1.add(BtnPikachu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 153, 38));

        BtnCharmander.setBackground(new java.awt.Color(255, 255, 255));
        BtnCharmander.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCharmander.setForeground(new java.awt.Color(0, 0, 0));
        BtnCharmander.setText("Charmander");
        BtnCharmander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCharmanderActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCharmander, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 153, 38));

        jTxtUser.setEditable(false);
        jTxtUser.setBackground(new java.awt.Color(255, 255, 255));
        jTxtUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTxtUser.setForeground(new java.awt.Color(0, 0, 0));
        jTxtUser.setBorder(null);
        jPanel1.add(jTxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 136, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnBatalla.setBackground(new java.awt.Color(255, 255, 255));
        BtnBatalla.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBatalla.setForeground(new java.awt.Color(0, 0, 0));
        BtnBatalla.setText("Empezar Batalla");
        BtnBatalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatallaActionPerformed(evt);
            }
        });
        jPanel2.add(BtnBatalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 153, 38));

        BtnAtaqueNormal.setBackground(new java.awt.Color(255, 255, 255));
        BtnAtaqueNormal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAtaqueNormal.setForeground(new java.awt.Color(0, 0, 0));
        BtnAtaqueNormal.setText("Placaje");
        BtnAtaqueNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtaqueNormalActionPerformed(evt);
            }
        });
        jPanel2.add(BtnAtaqueNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 153, 38));

        BtnLanzallamas.setBackground(new java.awt.Color(255, 255, 255));
        BtnLanzallamas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnLanzallamas.setForeground(new java.awt.Color(0, 0, 0));
        BtnLanzallamas.setText("Lanzallamas");
        BtnLanzallamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLanzallamasActionPerformed(evt);
            }
        });
        jPanel2.add(BtnLanzallamas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 150, 38));

        BtnCapturar.setBackground(new java.awt.Color(255, 255, 255));
        BtnCapturar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCapturar.setForeground(new java.awt.Color(0, 0, 0));
        BtnCapturar.setText("Capturar Pokemon");
        BtnCapturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCapturarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCapturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 160, 38));

        BtnAtaqueRapido.setBackground(new java.awt.Color(255, 255, 255));
        BtnAtaqueRapido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAtaqueRapido.setForeground(new java.awt.Color(0, 0, 0));
        BtnAtaqueRapido.setText("Ataque Rapido");
        BtnAtaqueRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtaqueRapidoActionPerformed(evt);
            }
        });
        jPanel2.add(BtnAtaqueRapido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 153, 38));

        BtnImpactrueno.setBackground(new java.awt.Color(255, 255, 255));
        BtnImpactrueno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnImpactrueno.setForeground(new java.awt.Color(0, 0, 0));
        BtnImpactrueno.setText("Impactrueno");
        BtnImpactrueno.setActionCommand("Impactrueno");
        BtnImpactrueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImpactruenoActionPerformed(evt);
            }
        });
        jPanel2.add(BtnImpactrueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 150, 38));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 530, 120));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Charmander.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pikachu.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("ELECCION DE POKEMON");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 28, -1, -1));

        TxtEnemigo.setEditable(false);
        TxtEnemigo.setBackground(new java.awt.Color(255, 255, 255));
        TxtEnemigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TxtEnemigo.setForeground(new java.awt.Color(0, 0, 0));
        TxtEnemigo.setBorder(null);
        TxtEnemigo.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(TxtEnemigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 180, 30));

        TxtVida.setEditable(false);
        TxtVida.setBackground(new java.awt.Color(255, 255, 255));
        TxtVida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TxtVida.setBorder(null);
        TxtVida.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(TxtVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 150, 30));

        TxtEnemigoNombre.setEditable(false);
        TxtEnemigoNombre.setBackground(new java.awt.Color(255, 255, 255));
        TxtEnemigoNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TxtEnemigoNombre.setForeground(new java.awt.Color(0, 0, 0));
        TxtEnemigoNombre.setText("Enemigo: Pikachu");
        TxtEnemigoNombre.setBorder(null);
        TxtEnemigoNombre.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        TxtEnemigoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEnemigoNombreActionPerformed(evt);
            }
        });
        jPanel1.add(TxtEnemigoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void Esconder() {
        jLabel1.setVisible(false);
        jLabel7.setVisible(false);
        BtnCharmander.setVisible(false);
        BtnPikachu.setVisible(false);
        TxtUsuario.setVisible(false);
        jLabel3.setVisible(false);
        jLabel8.setVisible(false);
        jLabel5.setVisible(false);
    }

    public void Esconder2() {
        jLabel4.setVisible(false);
        jLabel2.setVisible(false);
        BtnBatalla.setEnabled(false);
        jTxtUser.setVisible(false);
        jLabel6.setVisible(false);
        TxtVida.setVisible(false);
        TxtEnemigo.setVisible(false);
        BtnAtaqueNormal.setVisible(false);
        BtnCapturar.setVisible(false);
        BtnLanzallamas.setVisible(false);
        TxtEnemigoNombre.setVisible(false);
        BtnImpactrueno.setVisible(false);
        BtnAtaqueRapido.setVisible(false);
    }

    public void Ver() {
        jLabel4.setVisible(true);
        jLabel2.setVisible(true);
        BtnBatalla.setEnabled(true);
        jTxtUser.setVisible(true);
        jLabel6.setVisible(true);
        TxtVida.setVisible(true);
        TxtEnemigo.setVisible(true);
         TxtEnemigoNombre.setVisible(true);
    }
    private void BtnPikachuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPikachuActionPerformed

        String nombre = TxtUsuario.getText();

        yo.getPersonaje();
        yo.mostrar_mochila();

        // Resto del código para mostrar la mochila y realizar la batalla
        jTxtUser.setText(nombre);
        Esconder();
        Ver();
        BtnImpactrueno.setVisible(true);
        BtnAtaqueRapido.setVisible(true);
        BtnCapturar.setVisible(true);
    }//GEN-LAST:event_BtnPikachuActionPerformed

    private void BtnCharmanderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCharmanderActionPerformed
        // Permite al entrenador elegir entre Pikachu y Charmander al principio
        String nombre = TxtUsuario.getText();

        yo.getPersonaje2();
        yo.mostrar_mochila();

        // Resto del código para mostrar la mochila y realizar la batalla
        jTxtUser.setText(nombre);
        Esconder();
        Ver();
        BtnAtaqueNormal.setVisible(true);
        BtnCapturar.setVisible(true);
        BtnLanzallamas.setVisible(true);


    }//GEN-LAST:event_BtnCharmanderActionPerformed

    private void BtnBatallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatallaActionPerformed
        int opcion;
        do {
            // Mostrar opciones
            String[] opciones = {"Empezar una batalla", "Salir"};
            opcion = JOptionPane.showOptionDialog(
                    null,
                    "Elige una opción:",
                    "Batalla Pokémon",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    opciones,
                    opciones[0]
            );

            if (opcion == JOptionPane.YES_OPTION) {
                
                batalla.comienza(); // Llama al método comienza de la clase Batalla
                enBatalla = true;

            }
        } while (opcion != JOptionPane.NO_OPTION);
    }//GEN-LAST:event_BtnBatallaActionPerformed

    private void BtnAtaqueNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtaqueNormalActionPerformed
        if (enBatalla) { // Verifica si estás en una batalla
            batalla.pelea(1);
        }
    }//GEN-LAST:event_BtnAtaqueNormalActionPerformed

    private void BtnLanzallamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLanzallamasActionPerformed
        if (enBatalla) { // Verifica si estás en una batalla
            batalla.pelea(2);
        }
    }//GEN-LAST:event_BtnLanzallamasActionPerformed

    private void BtnCapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCapturarActionPerformed
        if (enBatalla) { // Verifica si estás en una batalla
            batalla.pelea(3);
        }
    }//GEN-LAST:event_BtnCapturarActionPerformed

    private void TxtEnemigoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEnemigoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEnemigoNombreActionPerformed

    private void BtnAtaqueRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtaqueRapidoActionPerformed
        // TODO add your handling code here:
         if (enBatalla) { // Verifica si estás en una batalla
            batalla.pelea(1);
        }
    }//GEN-LAST:event_BtnAtaqueRapidoActionPerformed

    private void BtnImpactruenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImpactruenoActionPerformed
        // TODO add your handling code here:
         if (enBatalla) { // Verifica si estás en una batalla
            batalla.pelea(2);
        }
    }//GEN-LAST:event_BtnImpactruenoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Elegir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Elegir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Elegir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Elegir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Elegir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BtnAtaqueNormal;
    public static javax.swing.JButton BtnAtaqueRapido;
    public static javax.swing.JButton BtnBatalla;
    public static javax.swing.JButton BtnCapturar;
    public static javax.swing.JButton BtnCharmander;
    public static javax.swing.JButton BtnImpactrueno;
    public static javax.swing.JButton BtnLanzallamas;
    public static javax.swing.JButton BtnPikachu;
    public static javax.swing.JTextField TxtEnemigo;
    public static javax.swing.JTextField TxtEnemigoNombre;
    public static javax.swing.JTextField TxtUsuario;
    public static javax.swing.JTextField TxtVida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField jTxtUser;
    // End of variables declaration//GEN-END:variables
}
